CREATE TABLE OCCURRENCES (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        DELIVERY_ID BIGINT NOT NULL,
        DESCRIPTION TEXT NOT NULL,
        REGISTRATION_DATE DATETIME NOT NULL,

        PRIMARY KEY(ID)
);

ALTER TABLE OCCURRENCES ADD CONSTRAINT FK_OCCURRENCE_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERYS (ID);